# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-11 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20191112_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(blank=True, to='firstapp.CartItem'),
        ),
    ]
